### ISSUE TITLE
build error.

### ISSUE THREAD

**Issue by cahitbeyaz** [mimoo/whiteboxDES#6]
hello,

project does not contains file : "tboxes.c" and "tboxes.h" files so build error occurs.

**Comment by mimoo** [comment]
yep, code is unfinished. the `tboxes.c` and `tboxes.h` are supposed to be generated by `LtablesGen.c`.

I suggest you to look at this code here: https://github.com/OpenWhiteBox/AES

it contains finished code for a whitebox AES

**Comment by cahitbeyaz** [comment]
actually i need whitebox des implementation can you give some instruction to build this on visual studio.

Thanx

**Comment by cahitbeyaz** [comment]
hi @mimoo i was able to generate tboxes.c but when i tried decryption in the main.c file. it only generates a  a file with null content.
